#!/usr/bin/env bash
# check-mir-autogen.sh
#
# Verify that auto-generated MIR test files in llvm/test/CodeGen/AMDGPU/ are
# up to date and that running update_mir_test_checks.py produces no warnings.
#
# Workflow:
#   1. Check no uncommitted changes in target files
#   2. Run llvm-lit on all files (pre-update)
#   3. Run update_mir_test_checks.py on all files, capture warnings
#   4. Report stale files (via git diff)
#   5. Run llvm-lit on all files again (post-update)
#   6. Print summary; exit non-zero if any issues found
#
# Usage:
#   check-mir-autogen.sh [OPTIONS] [FILE...]
#
# Options:
#   --build-dir DIR   LLVM build directory; derives llc and llvm-lit from it
#   --llc PATH        Explicit path to llc binary
#   --lit PATH        Explicit path to llvm-lit binary
#   --jobs N          Parallel jobs (default: nproc)
#   --list FILE       Read file list from FILE (one path per line)
#   FILE...           Explicit .mir files (overrides --list and auto-find)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# ---------------------------------------------------------------------------- #
# Defaults
# ---------------------------------------------------------------------------- #
BUILD_DIR=""
LLC=""
LIT=""
JOBS="$(nproc 2>/dev/null || echo 4)"
LIST_FILE=""
declare -a EXTRA_FILES=()

# ---------------------------------------------------------------------------- #
# Argument parsing
# ---------------------------------------------------------------------------- #
while [[ $# -gt 0 ]]; do
  case "$1" in
    --build-dir)
      BUILD_DIR="$2"; shift 2 ;;
    --llc)
      LLC="$2"; shift 2 ;;
    --lit)
      LIT="$2"; shift 2 ;;
    --jobs|-j)
      JOBS="$2"; shift 2 ;;
    --list)
      LIST_FILE="$2"; shift 2 ;;
    --help|-h)
      sed -n '/^# Usage:/,/^[^#]/{ /^#/s/^# \{0,1\}//p }' "${BASH_SOURCE[0]}"
      exit 0 ;;
    -*)
      echo "Unknown option: $1" >&2; exit 1 ;;
    *)
      EXTRA_FILES+=("$1"); shift ;;
  esac
done

# ---------------------------------------------------------------------------- #
# Resolve binaries
# ---------------------------------------------------------------------------- #
if [[ -n "$BUILD_DIR" ]]; then
  [[ -z "$LLC" ]] && LLC="$BUILD_DIR/bin/llc"
  [[ -z "$LIT" ]] && LIT="$BUILD_DIR/bin/llvm-lit"
fi
[[ -z "$LLC" ]] && LLC="$(command -v llc 2>/dev/null || true)"
[[ -z "$LIT" ]] && LIT="$(command -v llvm-lit 2>/dev/null || true)"

if [[ -z "$LLC" || ! -x "$LLC" ]]; then
  echo "ERROR: llc not found. Use --build-dir or --llc to specify its location." >&2
  exit 1
fi
if [[ -z "$LIT" || ! -x "$LIT" ]]; then
  echo "ERROR: llvm-lit not found. Use --build-dir or --lit to specify its location." >&2
  exit 1
fi

echo "Using llc:      $LLC"
echo "Using llvm-lit: $LIT"
echo "Parallel jobs:  $JOBS"
echo ""

# ---------------------------------------------------------------------------- #
# Collect file list
# ---------------------------------------------------------------------------- #
declare -a FILES=()

if [[ ${#EXTRA_FILES[@]} -gt 0 ]]; then
  FILES=("${EXTRA_FILES[@]}")
elif [[ -n "$LIST_FILE" ]]; then
  while IFS= read -r f; do
    [[ -n "$f" ]] && FILES+=("$f")
  done < "$LIST_FILE"
else
  echo "Discovering autogenerated MIR files..."
  while IFS= read -r f; do
    [[ -n "$f" ]] && FILES+=("$f")
  done < <(
    find "$REPO_ROOT/llvm/test/CodeGen/AMDGPU/" -name "*.mir" \
      -exec grep -l \
        "NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py" \
        {} \;
  )
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
  echo "ERROR: No files found to check." >&2
  exit 1
fi

echo "Checking ${#FILES[@]} autogenerated MIR file(s)."
echo ""

# ---------------------------------------------------------------------------- #
# Step 1: Pre-flight — no uncommitted changes
# ---------------------------------------------------------------------------- #
echo "==> Checking for uncommitted changes..."
DIRTY_FILES="$(
  cd "$REPO_ROOT"
  git diff --name-only -- "${FILES[@]}"
  git diff --cached --name-only -- "${FILES[@]}"
)"
if [[ -n "$DIRTY_FILES" ]]; then
  echo "ERROR: The following files have uncommitted changes." >&2
  echo "       Commit or stash them before running this script." >&2
  echo "$DIRTY_FILES" | sed 's/^/  /' >&2
  exit 1
fi
echo "    OK — no uncommitted changes."
echo ""

# ---------------------------------------------------------------------------- #
# Step 2: Pre-update lit run
# ---------------------------------------------------------------------------- #
echo "==> Running llvm-lit (pre-update)..."
PRE_LIT_LOG="$(mktemp)"
if ! "$LIT" -j"$JOBS" "${FILES[@]}" 2>&1 | tee "$PRE_LIT_LOG"; then
  echo ""
  echo "ERROR: Pre-update lit run failed. Fix test failures before updating." >&2
  rm -f "$PRE_LIT_LOG"
  exit 1
fi
rm -f "$PRE_LIT_LOG"
echo ""

# ---------------------------------------------------------------------------- #
# Step 3: Run update_mir_test_checks.py (parallel), capture warnings
# ---------------------------------------------------------------------------- #
echo "==> Running update_mir_test_checks.py on ${#FILES[@]} file(s) (jobs=$JOBS)..."

UPDATE_SCRIPT="$REPO_ROOT/llvm/utils/update_mir_test_checks.py"
TMPDIR_WARN="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_WARN"' EXIT

# Simple parallel job pool
run_update() {
  local f="$1"
  local warn_file="$2"
  python3 "$UPDATE_SCRIPT" --llc-binary "$LLC" "$f" 2>"$warn_file"
}

active=0
declare -A pids=()
declare -A warnfiles=()

for f in "${FILES[@]}"; do
  safe="${f//\//_}"
  wf="$TMPDIR_WARN/${safe}.warn"
  warnfiles["$f"]="$wf"
  run_update "$f" "$wf" &
  pids["$f"]=$!
  (( active++ )) || true

  if (( active >= JOBS )); then
    wait -n 2>/dev/null || wait   # wait for any child; bash <4.3 fallback
    (( active-- )) || true
  fi
done
wait

echo ""

# ---------------------------------------------------------------------------- #
# Step 4: Detect stale files and collect warnings
# ---------------------------------------------------------------------------- #
STALE_FILES=()
while IFS= read -r changed; do
  [[ -n "$changed" ]] && STALE_FILES+=("$changed")
done < <(
  cd "$REPO_ROOT"
  git diff --name-only -- "${FILES[@]}"
)

declare -A WARNINGS=()
for f in "${FILES[@]}"; do
  wf="${warnfiles[$f]}"
  if [[ -s "$wf" ]]; then
    WARNINGS["$f"]="$(cat "$wf")"
  fi
done

# ---------------------------------------------------------------------------- #
# Step 5: Post-update lit run
# ---------------------------------------------------------------------------- #
echo "==> Running llvm-lit (post-update)..."
POST_LIT_FAILED=0
"$LIT" -j"$JOBS" "${FILES[@]}" || POST_LIT_FAILED=1
echo ""

# ---------------------------------------------------------------------------- #
# Step 6: Summary
# ---------------------------------------------------------------------------- #
echo "======================================================================"
echo "SUMMARY"
echo "======================================================================"
echo "Files checked: ${#FILES[@]}"
echo ""

if [[ ${#WARNINGS[@]} -eq 0 ]]; then
  echo "Warnings:    none"
else
  echo "Warnings (${#WARNINGS[@]} file(s)):"
  for f in "${!WARNINGS[@]}"; do
    echo "  $f"
    echo "${WARNINGS[$f]}" | sed 's/^/    /'
  done
fi
echo ""

if [[ ${#STALE_FILES[@]} -eq 0 ]]; then
  echo "Stale files: none (all up to date)"
else
  echo "Stale files (${#STALE_FILES[@]} file(s) updated):"
  for f in "${STALE_FILES[@]}"; do
    echo "  $f"
  done
fi
echo ""

if [[ $POST_LIT_FAILED -eq 0 ]]; then
  echo "Post-update lit: PASSED"
else
  echo "Post-update lit: FAILED"
fi
echo "======================================================================"

# Exit non-zero if any issues
if [[ ${#WARNINGS[@]} -gt 0 || ${#STALE_FILES[@]} -gt 0 || $POST_LIT_FAILED -ne 0 ]]; then
  exit 1
fi
exit 0
